<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="">
  <meta property="og:type" content="">
  <meta property="og:url" content="">
  <meta property="og:image" content="">

  <link rel="manifest" href="<?php echo BASE_URL; ?>/site.webmanifest">
  <link rel="apple-touch-icon" href="<?php echo BASE_URL; ?>/icon.png">
  <!-- Place favicon.ico in the root directory -->

  <link rel="stylesheet" href="<?php echo BASE_URL; ?>/vendor/bootstrap.min.css">

  <meta name="theme-color" content="#fafafa">
</head>

<body>
  <!-- Render content -->
  <?php echo $context->content; ?>

  <script src="<?php echo BASE_URL; ?>/vendor/jquery.min.js"></script>
  <script src="<?php echo BASE_URL; ?>/vendor/bootstrap.bundle.min.js"></script>
</body>

</html>
