<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<?php $tools->link(''); ?>">QuizApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-between" id="navbarText">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="<?php $tools->link(''); ?>">Take a Quiz</a>
      </li>
    </ul>

    <?php
    if (!$tools->isLoggedIn()) {
    ?>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="<?php $tools->link('login'); ?>">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?php $tools->link('signup'); ?>">Signup</a>
        </li>
      </ul>
    <?php
    } else {
      $user = $tools->getCurrentUser();
    ?>
      <ul class="navbar-nav">
        <li class="nav-item">
          <span class="nav-link"><?php echo $user->email; ?></span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<?php $tools->link('logout'); ?>">Logout</a>
        </li>
      </ul>
    <?php
    }
    ?>
  </div>
</nav>

<?php
if (\property_exists($context, 'alerts')) {
  foreach ($context->alerts as &$alert) {
?>
    <div class="alert alert-<?php echo $alert->getSeverity(); ?>" role="alert">
      <?php echo $alert->getMessage(); ?>
    </div>
<?php
  }
}
?>

<?php
echo $context->content;
?>

<?php
return ['extends' => '_base'];
?>
