<div class="container mt-5">

    <div class="row">
        <?php
        foreach ($context->availableQuizzes as &$quiz) {
        ?>
            <div class="col-md-6">
                <div class="card shadow text-center">
                    <div class="card-body">
                        <h5 class="card-title"><?php $tools->text($quiz->name); ?></h5>
                        <p class="card-text">Author: <?php $tools->text($quiz->author); ?></p>
                        <a href="<?php $tools->link('quiz?' . \http_build_query([ 'id' => $quiz->id ])); ?>" class="btn btn-primary">Start</a>
                    </div>
                    <div class="card-footer text-muted">
                        <strong>~<?php $tools->text($quiz->duration); ?> minutes</strong> duration
                    </div>
                </div>
            </div>
        <?php
        }
        ?>
    </div>

</div>

<?php
return ['extends' => '_layout'];
?>
