<div class="container">

    <form method="POST">

        <h1 class="mt-5"><?php echo $context->quiz->name; ?></h1>
        <p class="lead">
            <ul class="list-group">
                <li class="list-group-item list-group-item-action"><strong>~<?php echo $context->quiz->duration; ?> minutes</strong> duration</li>
                <li class="list-group-item list-group-item-action">Only <strong>multiple-choice</strong> questions</li>
                <li class="list-group-item list-group-item-action">Created by <strong><?php echo $context->quiz->author; ?></strong></li>
            </ul>
        </p>

        <h2 class="mt-3 text-muted">Questions</h2>

        <?php
        foreach ($context->quiz->questions as $index => &$question) {
        ?>
            <div class="card text-center shadow my-3">
                <div class="card-body">
                    <h5 class="card-title"><?php echo $index + 1; ?>. Which SQL statement is used to extract data from a database?</h5>
                </div>
                <ul class="list-group">
                    <li class="list-group-item list-group-item-action" onclick="this.getElementsByTagName('input')[0].click(event)">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="q_<?php echo $index; ?>" id="q_<?php echo $index; ?>" value="A">
                            <label class="form-check-label" for="q_<?php echo $index; ?>">SELECT</label>
                        </div>
                    </li>
                    <li class="list-group-item list-group-item-action" onclick="this.getElementsByTagName('input')[0].click(event)">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="q_<?php echo $index; ?>" id="q_<?php echo $index; ?>" value="B">
                            <label class="form-check-label" for="q_<?php echo $index; ?>">OPEN</label>
                        </div>
                    </li>
                    <li class="list-group-item list-group-item-action" onclick="this.getElementsByTagName('input')[0].click(event)">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="q_<?php echo $index; ?>" id="q_<?php echo $index; ?>" value="C">
                            <label class="form-check-label" for="q_<?php echo $index; ?>">EXTRACT</label>
                        </div>
                    </li>
                    <li class="list-group-item list-group-item-action" onclick="this.getElementsByTagName('input')[0].click(event)">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="q_<?php echo $index; ?>" id="q_<?php echo $index; ?>" value="D">
                            <label class="form-check-label" for="q_<?php echo $index; ?>">GET</label>
                        </div>
                    </li>
                </ul>
            </div>
        <?php
        }
        ?>

        <div class="text-right">
            <button type="submit" value="submit" class="btn btn-primary btn-lg mt-3">Submit</button>
        </div>

    </form>

</div>

<?php
return ['extends' => '_layout'];
?>
