<div class="container">

    <h1 class="mt-5">Signup</h1>

    <form method="POST">
        <div class="form-group">
            <label for="id_email">Email address</label>
            <input type="email" class="form-control" id="id_email" name="email" aria-describedby="id_email_help" placeholder="Enter email">
            <small id="id_email_help" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="id_password">Password</label>
            <input type="password" class="form-control" id="id_password" name="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary">Log in</button>
    </form>

</div>

<?php
return ['extends' => '_layout'];
?>
